### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addMarkerLayer' of undefined

### ISSUE THREAD

**Issue by xavidiaz** [shillingp/atom-lorem#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [lorem](https://github.com/shillingp/atom-lorem) package 1.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'addMarkerLayer' of undefined

```
At /Users/Javi/.atom/packages/lorem/lib/lorem.js:141

TypeError: Cannot read property 'addMarkerLayer' of undefined
    at Object.createCursorLayer (/packages/lorem/lib/lorem.js:141:25)
    at Object.handleLorem (/packages/lorem/lib/lorem.js:156:24)
    at /packages/lorem/lib/lorem.js:101:43)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  7x -7:55.9.0 core:move-right (input.hidden-input)
     -7:54 intentions:highlight (input.hidden-input)
     -7:53.5.0 lorem:catch-command (input.hidden-input)
     -7:46.1.0 intentions:highlight (input.hidden-input)
     -7:45 lorem:catch-command (input.hidden-input)
     -7:39.8.0 intentions:highlight (input.hidden-input)
     -7:39.5.0 lorem:catch-command (input.hidden-input)
     -7:06.6.0 settings-view:open (input.hidden-input)
     -6:02.5.0 intentions:highlight (input.hidden-input)
     -5:53.4.0 core:confirm (input.hidden-input)
     -5:44.5.0 intentions:highlight (input.hidden-input)
 37x -4:01.4.0 core:backspace (input.hidden-input)
     -3:50.1.0 editor:delete-to-beginning-of-word (input.hidden-input)
  2x -2:02.7.0 settings-view:open (input.hidden-input)
  7x -0:41.5.0 core:backspace (input.hidden-input)
     -0:30.4.0 lorem:catch-command (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
busy-signal 1.3.0 
emmet 2.4.3 
file-icons 2.0.17 
git-plus 7.3.3 
intentions 1.1.2 
javascript-snippets 1.2.1 
keybinding-cheatsheet 0.1.1 
linter 2.1.0 
linter-bootlint 1.0.4 
linter-csslint 1.3.4 
linter-javac 1.9.4 
linter-jshint 3.0.3 
linter-jsonlint 1.3.0 
linter-liferay 2.4.0 
linter-stylelint 3.9.0 
linter-ui-default 1.2.1 
lorem 1.1.1 
markdown-preview-plus 2.4.9 
minimap-highlight-selected 4.5.0 
script 3.14.1 
```

**Comment by shillingp** [comment]
@xavidiaz thank you for posting this issue. Can i confirm that this is only happening when there is no text editor pane/files open?
