### ISSUE TITLE
Uncaught TypeError: editor.languageMode.toggleLineCommentForBufferRow is not a function

### ISSUE THREAD

**Issue by idoalit** [shillingp/atom-lorem#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: [lorem](https://github.com/shillingp/atom-lorem) package 1.3.0

### Stack Trace

Uncaught TypeError: editor.languageMode.toggleLineCommentForBufferRow is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:948

TypeError: editor.languageMode.toggleLineCommentForBufferRow is not a function
    at /packages/lorem/lib/lorem.js:181:31
    at Array.forEach (native)
    at /packages/lorem/lib/lorem.js:167:15
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:941:24)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1811:30)
    at Object.handleLorem (/packages/lorem/lib/lorem.js:166:12)
    at HTMLElement.loremCatchCommand (/packages/lorem/lib/lorem.js:103:43)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -2:28.3.0 editor:newline (input.hidden-input)
     -2:27.2.0 core:paste (input.hidden-input)
     -2:20.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:28 editor:select-to-first-character-of-line (input.hidden-input)
  2x -1:27.1.0 core:backspace (input.hidden-input)
     -1:23.9.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -1:22.1.0 core:backspace (input.hidden-input)
     -1:08.3.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -1:07.7.0 core:backspace (input.hidden-input)
     -1:06.9.0 editor:newline (input.hidden-input)
     -1:05.9.0 core:paste (input.hidden-input)
     -0:37.3.0 editor:select-to-end-of-line (input.hidden-input)
     -0:36.4.0 core:backspace (input.hidden-input)
     -0:26.5.0 lorem:catch-command (input.hidden-input)
  2x -0:21.6.0 core:backspace (input.hidden-input)
     -0:16.3.0 lorem:catch-command (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
autocomplete-emojis 2.5.0 
block-comment 0.4.3 
comment-headers 2.15.0 
emoji-syntax 1.7.2 
file-header 1.13.8 
file-icons 2.1.16 
lorem 1.3.0 
minimap 4.29.7 
multi-cursor 2.1.5 
php-getters-setters 0.5.5 
pigments 0.40.2 
react 0.17.0 
react-snippets 1.0.1 
sublime-block-comment 0.5.1 
wordpress-autocomplete 1.2.0 
```

**Comment by shillingp** [comment]
Many thanks @idoalit was an outdated call. Will implement a spec for this  in future
